name: Deploy via SSH

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name'
        required: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - name: open zip if exists
        run: |
          sudo apt-get install unzip
          if [ -f folder/task2/${{ inputs.package }}.zip ]; then
            echo "File exists"
            unzip -o folder/task2/${{ inputs.package }}.zip
            echo "Hello, World!" > script.2_1.txt
            zip folder/task2/${{ inputs.package }}_1.zip script.2_1.txt script2.txt
          else
            echo "File does not exist"
            echo "Hello, World!" > script.2_1.txt
            zip folder/task2/${{ inputs.package }}_1.zip script.2_1.txt
          fi
      - name: copy files      
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "nicolas.torres.ar@gmail.com"
          git add folder/task2/${{ inputs.package }}_1.zip
          git commit -m "add script.2_1.txt to ${{ inputs.package }}_1.zip"
      - name: push changes
        run: |
          git push origin main
    